export enum StadisticType {
    TotalMatches = 'total-matches',
    LeagueMatches = 'league-matches',
    FriendlyMatches = 'friendly-matches',
    WonMatches = 'won-matches',
    TiedMatches = 'tied-matches',
    LostMatches = 'lost-matches',
    TitularPlayer = 'titular-player',
    SubstitutePlayer = 'substitute-player',
    Goals = 'goals',
    Assistance = 'assistance',
    Time = 'time',
    SanctionsMatches = 'sanctions-matches',
    YellowCards = 'yellow-cards',
    RedCards = 'red-cards',
    ThrownPenalty = 'shot-penalty',
    GoalsPenalty = 'goals-penalty',
    ProvokedPenalty = 'provoked-penalty',
    PenaltiesSaved = 'penalties-saved'
}
